[package]
name = "rust_test_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
chrono = { version = "0.4", features = ["serde"] }
